### ISSUE TITLE
question

### ISSUE THREAD

**Issue by XGuider** [suljaxm/HandWriting#1]
dontLoveBugs/DORN_pytorch ,can you run?
i used resnet101-imagenet.pth,it have three question.

RuntimeError: Error(s) in loading state_dict for ResNet:
	size mismatch for conv1.weight: copying a param of torch.Size([64, 3, 3, 3]) from checkpoint, where the shape is torch.Size([64, 3, 7, 7]) in current model.
	size mismatch for layer1.0.conv1.weight: copying a param of torch.Size([64, 128, 1, 1]) from checkpoint, where the shape is torch.Size([64, 64, 1, 1]) in current model.
	size mismatch for layer1.0.downsample.0.weight: copying a param of torch.Size([256, 128, 1, 1]) from checkpoint, where the shape is torch.Size([256, 64, 1, 1]) in current model.

Could you please help me?

**Comment by bluizh** [comment]
Sorry, but I was the above steps debugging success. Maybe you'd better ask the author.

**Comment by bluizh** [comment]
I think your problem is that the channel of the tensor does not correspond to each other. You can output the tensor size of each layer and see which is the error. @XGuider
